Add support for Gardener pre-release integration test pipeline
gardenlinux/glci-legacy pull request #25
Opened 2023-10-31 10:38 UTC by MrBatschner

**What this PR does / why we need it**:

This PR adds support for a Gardener integration test pipeline that supports testing Garden Linux versions that have not been release (yet). The changes include a dedicated publishing config and several changes that allow for publishing temporary artefcats to non-productive locations.

Supports AWS only at the moment, the other platforms will follow in seperate PRs.

**Special notes for your reviewer**:

You might want to review the individual commits separately and have a look at their commit messages to understand their intentions.

This PR should not be squashed, the commits should be left intact.

**Release note**:

```feature operator
The glci publishing gear now supports publishing and cleaning of temporary artefacts that can be used in Gardener integration tests.
```

2023-11-02 10:52 UTC, MrBatschner commented
/ready
/invite @ccwienk 
/invide @zkdev

2023-11-10 13:42 UTC, ccwienk requested changes

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +    if len(target_manifest_buckets) == 0:
nit: it is more "pythonic" to just use `if not target_manifest_buckets`
also: preferably, passing-in empty target-buckets-iterable should be considered an error; it appears unintuitive to me to fallback to targetting source-buckets

2023-11-10 13:42 UTC, ccwienk commented on glci/alicloud.py
> +            if self.regions_to_copy_to != None:
style: according to pep8, you should use identity-comparison for singletons such as `None` (is instead of == / !=)

however, this might even be improved:

```
# single if
if self.regions_to_copy_to and region_id in self.regions_to_copy_to:
  ...

# or: initialise region_to_copy_to as empty collection
if region in self.regions_to_copy_to:
 ...
```

2023-11-10 13:42 UTC, ccwienk commented on glci/aws.py
> +        if regions_to_include != None:
style: use `is` | `is not` (or rather: omit comparison to None)

2023-11-10 13:42 UTC, ccwienk commented on glci/model.py
> +    copy_regions: typing.Optional[list[str]]
nit: if you initialise to empty list | tuple you might omit checking for None (-> less special-cases)

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +        choices=('all', 'versions', 'versions-and-commits', 'latest'),
considering you sort by version, this should rather be called `greatest`

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +    manifests.sort(key=lambda v: float(v.version))
rather use cc-util's `version.parse_to_semver` (parses to "relaxed semver"). or: split into two integers, and implement custom comparison. said module btw also features `version.greatest_version`. if you would prefer to not introduce this dependency, feel free to copy-paste required parts from version.py

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +    if parsed.print == 'latest':
greatest

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +                f.write(yaml.dump(v.__dict__))
safe_dump? also, preferably use `dataclasses.asdict`

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +    if not bool(parsed.infile):
for convenience, you might also check for `sys.stdin.isatty()` and read from stdin in this case

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +    import replicate    # late import because unneeded for the other functions
hmm.... I guess late-imports are okay-ish (not a nice codestyle). is this motivated by significant performance costs from those imports?

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +        '--ctx-repo',
nit: since rename from "CNUDIE" -> OCM, those are actually called "OCM Repository" / -ies (so --ocm-repo might be nicer)

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +        with open(parsed.infile[0]) as f:
using YAML is fine. however: would a plain text file only containing version be easier for local usage?

2023-11-10 13:42 UTC, ccwienk commented on .cicd-cli.py
> +        raise RuntimeError(f"need to provide either --version or --infile parameter")
nit: why not call it `--version-file`?

2023-11-10 13:42 UTC, ccwienk commented on component_descriptor.py
> +        ctx_repository: str,
not sure whether this function is actually useful (that's what component-descriptor-lookups are for..)

rather define a helperfunction that will create and return a component-lookup.

2023-11-10 13:42 UTC, ccwienk commented on component_descriptor.py
> +        default_ctx_repo=cm.OciRepositoryContext(baseUrl=ctx_repository),
please no longer use default_ctx_repo. this is deprecated (yes, it is not yet marked as such).

instead, pass-in an ocm-repository-lookup:

```
ocm_repo_lookup = cnudie.retrieve.ocm_repository_lookup(ocm_repository_url)

component_descriptor_lookup = cnudie.retrieve.create_default_component_descriptor_lookup(
 ocm_repository_lookup=ocm_repo_lookup,
)
```

`component_descriptor_lookup` btw offers some convenience for doing lookups:

```
# use single str
comp = lookup('github.com/gardenlinux/gardenlinux:1300.0')+
# use two-tuple (name, version)
comp = lookup(('github.com/gardenlinux/gardenlinux', '1300.0')
# ... also allowed: Component, ComponentDescriptor, ComponentIdentity, ComponentReference

2023-11-10 13:42 UTC, ccwienk commented on glci/aws.py
> +    if len(response["Images"]) > 0:
style: need not check for leng (if response['Images']: ...)

2023-11-10 13:42 UTC, ccwienk commented on glci/aws.py
> +    return snapshots
style: might use a generator (yield)

2023-11-10 13:42 UTC, ccwienk commented on glci/aws.py
> +        client: 'botocore.client.EC2',
style: instead of passing-around dry_run-flags, you might pass-in dummy-clients (might not be a good idea overall, though)

2023-11-10 13:42 UTC, ccwienk commented on glci/aws.py
> +    executor = concurrent.futures.ThreadPoolExecutor(max_workers=len(images))
TPE will default to max_workers equal number of logical CPUs. this might be a better choice than number of images. unless you do not care about number of vCPUs and really one a dedicated thread per image

2023-11-10 13:42 UTC, ccwienk commented on glci/aws.py
> +                dry_run=False,
should this be made a parameter that can also be passed to calling function?

2023-11-10 13:42 UTC, ccwienk commented on cleanup.py
> +## functions moved over from clean.py
I think this comment is not helpful (or actually confusing) 🤔

2023-11-14 07:52 UTC, AndreasBurger commented on .cicd-cli.py
> +    repository_context = component_descriptor.component.repositoryContexts[0].baseUrl
consider using current_repository_context (https://github.com/gardener/cc-utils/blob/a679e13c4a6fce91e0301ae407ab513466657414/gci/componentmodel.py#L517)

2023-11-14 09:59 UTC, MrBatschner commented on .cicd-cli.py
> +    if len(target_manifest_buckets) == 0:
The reason for the - at first unintuitive - falling back to source manifest buckets is this (see line 861):
- In the normal case (publishing for productive usage), we have one release manifest which lives in the `source_manifest_bucket`. We publish the artefacts and then update the release manifest in the `source_manifest_bucket`. This is how it has been before this PR and how it should remain for productive publishing.
- In the integration test case (only temporary publishing for an integration test with timely cleanup/deletion of the published artefacts after), we have a copy of the release manifest containing the publish information just for the artefacts published for testing. That copy goes into a `target_manifest_bucket`, leaving the original manifest in the `source_manifest_bucket` untouched - the original manifest in the `source_manifest_bucket` should only contain publish information about artefacts that were released for productive usage.
- If no `target_manifest_bucket` is specified in the `publishing-cfg`, no copy of the release-manifest should be created. Instead, the original release manifest (the one in the `source_manifest_bucket`) should be amended with the publish-information.
- Thus, when it comes to updating the release manifest, if no dedicated `target_manifest_bucket` is specified, the `source_manifest_bucket` also becomes the `target_manifest_bucket` for the updated release manifest.

2023-11-14 11:47 UTC, MrBatschner commented on .cicd-cli.py
> +    manifests.sort(key=lambda v: float(v.version))
Actually, I am not entirely sure what I was thinking when I was using a `float` for it...

2023-11-14 11:51 UTC, MrBatschner commented on .cicd-cli.py
> +    import replicate    # late import because unneeded for the other functions
These modules (`replicate`, `publish`, `cleanup`) will eventually import lots of the hyperscaler SDKs. For something simple as `ls_manifests`, which only requires boto3, the presence of Azure or AliCloud SDK modules should not be a hard requirement - hence the late imports. I guess this is one of the tradeoffs to be considered when using the busybox swiss-army knife approach...

2023-11-14 13:15 UTC, MrBatschner commented on glci/aws.py
> +                dry_run=False,
In this case probably not. Uploading and publishing in a dry-run fashion does not really make sense to me and if something goes wrong, the left-overs should be cleaned wet. In this particular instance, I would prefer not to change the usage of the dry-run flag.

2023-11-14 15:13 UTC, MrBatschner commented on glci/aws.py
> +    return snapshots
If the generator is passed into the `_delete_snapshots()` (I guess the most meaningful way of using a generator),  `ec2.describe_images()` to obtain the snapshot IDs would be called AFTER `ec2.deregister_image()` which - depending how fast AWS is with actually deregistering the image - could lead to an empty response and dangling snapshots.

2023-11-15 08:13 UTC, MrBatschner commented on .cicd-cli.py
> +        with open(parsed.infile[0]) as f:
True. Somehow, I wanted to have this future proof already in case the committish is required in addition to the version and in that case, I would prefer a structured file-format over a plain text file.

2023-11-15 08:15 UTC, MrBatschner commented on glci/aws.py
> +        client: 'botocore.client.EC2',
Brilliant idea, something I will probably implement in a new, separate PR.

2023-11-15 08:18 UTC, MrBatschner commented
@ccwienk, @AndreasBurger : I addressed your feedback, PTAL. I will eventually squash the feedback commits before merging but wanted to keep them separate for now to simplify the review for you.

2023-11-20 08:42 UTC, ccwienk commented on glci/aws.py
> +    return snapshots
the caller can enforce immediate execution of the generator by calling the function like so:
```
snapshots = tuple(_get_snapshots_for_image(...))
```

anyhow: it is of course okay to iteratively create a list and return it (and in this specific case).

2023-11-20 08:44 UTC, ccwienk commented on glci/aws.py
> +        client: 'botocore.client.EC2',
yeah, it will have limitations if responses of such dummy-clients are required. although that might of course also be dealt somehow.

2023-11-20 08:44 UTC, ccwienk approved these changes

2023-11-20 08:50 UTC, merged