switch GCR -> Artifact-Registry
gardenlinux/glci-legacy pull request #31
Opened 2023-12-07 16:34 UTC by ccwienk

GCR has been deprecated [0] in favour of Artifact-Registry.

Thus, change push-targets for OCI-Images:

- europe-docker.pkg.dev/gardener-project/snapshots for snapshots
- europe-docker.pkg.dev/gardener-project/releases for releases
- europe-docker.pkg.dev/gardener-project/public for combined view of snapshots + releases

[0]
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

**Release note**:

```breaking operator
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.

```

2023-12-07 18:10 UTC, MrBatschner requested changes

2023-12-07 18:10 UTC, MrBatschner commented on publishing-cfg.yaml
> -    component_repository_cfg_name: 'gardenlinux-test'
`gardenlinux-test` pointed to repository `eu.gcr.io/gardenlinux/integration-tests` - the cds created by this publishing config should not live in the `gardener-project` universe.

2023-12-07 18:10 UTC, MrBatschner commented on .cicd-cli.py
> -        ocm_cfg = cfg_factory.ctx_repository(cfg.ocm.component_repository_cfg_name)
Just for clarification: before, `cfg_factory.ctx_repository()` took the name of a config item and resolved that to a repo context and now it takes the base-url of a repository and just returns that url?

2023-12-07 19:51 UTC, ccwienk commented on publishing-cfg.yaml
> -    component_repository_cfg_name: 'gardenlinux-test'
valid point. in that case, I think we will need an artifact-registry for `gcp/gardenlinux`.

2023-12-07 19:52 UTC, ccwienk commented on .cicd-cli.py
> -        ocm_cfg = cfg_factory.ctx_repository(cfg.ocm.component_repository_cfg_name)
we might reconsider whether a cfg-element is actually adequate in this special case

2023-12-08 10:15 UTC, MrBatschner requested changes
Pasted the ocm_repository for GL tests as suggestion inline.
LGTM otherwise.

2023-12-08 10:15 UTC, MrBatschner commented on publishing-cfg.yaml
> +    ocm_repository: europe-docker.pkg.dev/gardener-project/snapshots
```suggestion
    ocm_repository: europe-docker.pkg.dev/sap-se-gcp-gardenlinux/tests
```

2023-12-11 09:11 UTC, MrBatschner approved these changes
/lgtm

2023-12-11 09:11 UTC, merged